В задании нужно загрузить датасет с данными оттока и ответить на несколько вопросов (написать код). При этом сам датасет уже есть и его необязательно качать с репозитория

Цель задания: проверить базовые навыки работы студентов с Pandas, умение проводить такой же базовый EDA (exploratory data analysis), делать feature engineering и обучать и валидировать модель.

Список столбцов с типами данных в датасете:

- customerID           object
- gender               object
- SeniorCitizen         int64
- Partner              object
- Dependents           object
- tenure                int64
- PhoneService         object
- MultipleLines        object
- InternetService      object
- OnlineSecurity       object
- OnlineBackup         object
- DeviceProtection     object
- TechSupport          object
- StreamingTV          object
- StreamingMovies      object
- Contract             object
- PaperlessBilling     object
- PaymentMethod        object
- MonthlyCharges      float64
- TotalCharges         object
- Churn                object

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("D:\Study\Machine Learning in Business\Manual\Lesson1/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head(3)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   

      PaymentMethod MonthlyCharges  TotalCharges Churn  
0  Electronic check          29.85         29.85    No  
1      Mailed check          56.95        1889.5    No  
2      Mailed check          53.85        108.15   Yes  

[3 rows x 21 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


#### 1. Какое соотношение мужчин и женщин в представленном наборе данных?

In [4]:
df['gender'].value_counts()

Male      3555
Female    3488
Name: gender, dtype: int64

#### 2. Какое количество уникальных значений у поля InternetService?

In [5]:
print(f"уникальных значений {df['InternetService'].nunique()}")
df['InternetService'].value_counts()

уникальных значений 3


Fiber optic    3096
DSL            2421
No             1526
Name: InternetService, dtype: int64

#### 3. Выведите статистики по полю TotalCharges (median, mean, std).

In [6]:
df['TotalCharges'].describe()

count     7043
unique    6531
top           
freq        11
Name: TotalCharges, dtype: object

В чем странность того, что вы получили? (подсказка: смотреть нужно на тип данных)

Тип данных object относится к нечисловым типам данных. Это тип данных, который может содержать любые данные (строки, списки, словари, функции) - менее эффективен по памяти и времени выполнения

#### 4. Сделайте замену значений поля PhoneService на числовые (Yes->1, No->0)

In [7]:
df['PhoneService'].value_counts()

Yes    6361
No      682
Name: PhoneService, dtype: int64

In [8]:
df['PhoneService'] = (df['PhoneService'] == 'Yes').astype(int)

In [9]:
df['PhoneService'].value_counts()

1    6361
0     682
Name: PhoneService, dtype: int64

#### 5. Сделайте замену пробелов в поле TotalCharges на np.nan и приведите поле к типу данных float32. Затем заполните оставшиеся пропуски значением 0 с помощью метода fillna у столбца. Снова выведите статистики и сравните с тем, что вы видели в вопросе 3

In [10]:
df['TotalCharges'].describe()

count     7043
unique    6531
top           
freq        11
Name: TotalCharges, dtype: object

In [11]:
df['TotalCharges'] = df['TotalCharges'].apply(lambda x: float(x) if (x and x.strip()) else np.nan)
df['TotalCharges'] = df['TotalCharges'].astype(np.float32)
df[['TotalCharges']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   TotalCharges  7032 non-null   float32
dtypes: float32(1)
memory usage: 27.6 KB


In [12]:
df['TotalCharges'].isna().sum()

11

In [13]:
df['TotalCharges'].fillna(0, inplace=True)
df['TotalCharges'].isna().sum()

0

#### 6. Сделайте замену значений поля Churn на числовые (Yes -> 1, No - 0)

In [15]:
df['Churn'].value_counts()

No     5174
Yes    1869
Name: Churn, dtype: int64

In [16]:
df['Churn'] = (df['Churn'] == 'Yes').astype(int)
df['Churn'].value_counts()

0    5174
1    1869
Name: Churn, dtype: int64

#### 7. Сделайте замену значений полей StreamingMovies, StreamingTV, TechSupport на числовые (Yes -> 1, No -> 0, No internet service->0)

In [17]:
df['StreamingMovies'].unique(), df['StreamingTV'].unique(), df['TechSupport'].unique()

(array(['No', 'Yes', 'No internet service'], dtype=object),
 array(['No', 'Yes', 'No internet service'], dtype=object),
 array(['No', 'Yes', 'No internet service'], dtype=object))

In [18]:
df[['StreamingMovies', 'StreamingTV', 'TechSupport']] = (
    df[['StreamingMovies', 'StreamingTV', 'TechSupport']]
    .replace({'Yes': 1, 'No': 0, 'No internet service': 0})
)

In [19]:
df['StreamingMovies'].unique(), df['StreamingTV'].unique(), df['TechSupport'].unique()

(array([0, 1], dtype=int64),
 array([0, 1], dtype=int64),
 array([0, 1], dtype=int64))

#### 8. Заполните пропуски в поле PhoneService значением 0 

In [20]:
df['PhoneService'].unique()

array([0, 1])

In [21]:
df['PhoneService'].value_counts()

1    6361
0     682
Name: PhoneService, dtype: int64

In [22]:
df['PhoneService'].fillna(0, inplace=True)
df['PhoneService'].isna().sum()

0

#### 9. Для нашего датасета оставьте только указанный ниже список полей, удалив все другие и выведите верхние 3 строки

In [23]:
columns = ['gender', 'tenure', 'PhoneService', 'TotalCharges', 
           'StreamingMovies', 'StreamingTV', 'TechSupport', 'Churn']

df = df[columns]
df.head(3)

gender  tenure  PhoneService  TotalCharges  StreamingMovies  StreamingTV  \
0  Female       1             0     29.850000                0            0   
1    Male      34             1   1889.500000                0            0   
2    Male       2             1    108.150002                0            0   

   TechSupport  Churn  
0            0      0  
1            0      0  
2            0      1

#### 10. Разделите датасет на тренировочную и тестовую выборку.


In [24]:
features = ['gender', 'tenure', 'PhoneService', 'TotalCharges', 'StreamingMovies', 'StreamingTV', 'TechSupport']
target = 'Churn'

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[features], df[target],
                                                    test_size=0.3, 
                                                    shuffle=True,
                                                    random_state=47)

In [25]:
X_train.shape, X_test.shape

((4930, 7), (2113, 7))

#### 11. соберите pipeline для поля gender (нужно разобраться и изучить https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html ) из классов ColumnSelector и OHEEncoder, которые уже написаны ниже заранее

In [26]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline

class ColumnSelector(BaseEstimator, TransformerMixin):
    """
    Transformer to select a single column from the data frame to perform additional transformations on
    """
    def __init__(self, key):
        self.key = key

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X[self.key]
    
class NumberSelector(BaseEstimator, TransformerMixin):
    """
    Transformer to select a single column from the data frame to perform additional transformations on
    Use on numeric columns in the data
    """
    def __init__(self, key):
        self.key = key

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X[[self.key]]
    
class OHEEncoder(BaseEstimator, TransformerMixin):
    def __init__(self, key):
        self.key = key
        self.columns = []

    def fit(self, X, y=None):
        self.columns = [col for col in pd.get_dummies(X, prefix=self.key).columns]
        return self

    def transform(self, X):
        X = pd.get_dummies(X, prefix=self.key)
        test_columns = [col for col in X.columns]
        for col_ in self.columns:
            if col_ not in test_columns:
                X[col_] = 0
        return X[self.columns]

In [27]:
gender = Pipeline([
    ('column_selector', ColumnSelector(key='gender')),
    ('ohe', OHEEncoder(key='gender'))    
])

#### 12. Вызовите метод fit_transform у пайплайна gender и передайте туда нашу тренировочную выборку (пример по ссылке из документации https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html#sklearn.pipeline.Pipeline.fit)

In [28]:
gender.fit_transform(X_train)

gender_Female  gender_Male
649               0            1
2371              1            0
84                1            0
5079              0            1
2790              1            0
...             ...          ...
6728              1            0
3336              1            0
6471              0            1
1926              0            1
5255              1            0

[4930 rows x 2 columns]

#### 13. Здесь код писать уже не нужно (все сделано за вас). К полю tenure применяем StandardScaler (нормируем и центрируем). Ссылка - https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html


Вопрос - в каких случаях это может быть полезно?

StandardScaler полезен, когда нужно нормализовать данные перед использованием в модели ML - приводит все признаки к одному масштабу и среднему значению. Это позволяет модели равномерно учитывать все признаки при обучении.

In [29]:
from sklearn.preprocessing import StandardScaler

tenure =  Pipeline([
                ('selector', NumberSelector(key='tenure')),
                ('standard', StandardScaler())
            ])

#### 14. Напишите аналогичный (как для tenure) преобразователь поля TotalCharges

In [30]:
TotalCharges =  Pipeline([
    ('selector', NumberSelector(key='TotalCharges')),
    ('standard', StandardScaler())
])

Объединение всех "кубиков" очень легко сделать таким образом

In [31]:
from sklearn.pipeline import FeatureUnion

number_features = Pipeline([
                ('selector', ColumnSelector(key=['PhoneService',
                                                 'StreamingMovies', 'StreamingTV', 
                                                 'TechSupport']))
            ])

In [32]:
feats = FeatureUnion([('tenure', tenure),
                      ('TotalCharges', TotalCharges),
                      ('continuos_features', number_features),
                      ('gender', gender)])
feature_processing = Pipeline([('feats', feats)])

На этом этапе что мы сделали:

1. написали преобразователь поля gender, который делает OHE кодирование
2. написали преобразователь для поля tenure, который нормирует и центрирует его 
3. повторили п. 2 для поля TotalCharges
3. для всех остальных просто взяли признаки как они есть, без изменений

У нас уже готов наш пайплайн, который преобразовывает признаки. Давайте обучим модель поверх него. В качестве модели возьмем RandomForestClassifier

In [33]:
from sklearn.ensemble import RandomForestClassifier

pipeline = Pipeline([
    ('features', feats),
    ('classifier', RandomForestClassifier(random_state=42)),
])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('features',
                 FeatureUnion(transformer_list=[('tenure',
                                                 Pipeline(steps=[('selector',
                                                                  NumberSelector(key='tenure')),
                                                                 ('standard',
                                                                  StandardScaler())])),
                                                ('TotalCharges',
                                                 Pipeline(steps=[('selector',
                                                                  NumberSelector(key='TotalCharges')),
                                                                 ('standard',
                                                                  StandardScaler())])),
                                                ('continuos_features',
                                                 Pipeline(steps=[('selector',
          

#### 15. Сделайте прогноз вероятности оттока для X_test с помощью нашего предобученного на предыдущем шаге пайплайна и убедитесь что вам возвращаются вероятности для 2 классов

In [34]:
preds = pipeline.predict_proba(X_test)
preds

array([[1.  , 0.  ],
       [0.82, 0.18],
       [0.81, 0.19],
       ...,
       [0.99, 0.01],
       [0.52, 0.48],
       [0.11, 0.89]])

#### 16. Посчитайте метрики качества получившейся модели (roc_auc)

In [35]:
from sklearn.metrics import roc_auc_score

roc_auc = roc_auc_score(y_test, preds[:, 1])
print(roc_auc)

0.7752298130693991


### Сохраним наш пайплайн

In [36]:
!pip install dill

In [37]:
import dill
with open("model_RF.dill", "wb") as f:
    dill.dump(pipeline, f)